select * from TXN_DB.HARMONIZED.FLATTENED_TRANSACTIONS_V_STREAM;

CREATE OR REPLACE TASK TASK_UPDATE_COF_SCORES
WAREHOUSE = TXN_WH
SCHEDULE = '5 minute'
WHEN
  SYSTEM$STREAM_HAS_DATA('TXN_DB.HARMONIZED.FLATTENED_TRANSACTIONS_V_STREAM')
AS
CALL TXN_DB.HARMONIZED.INCREMENTAL_SCORING_SP();

ALTER TASK TASK_UPDATE_COF_SCORES RESUME;

show tasks;


